MyPlate/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomePage.as_view(), name='index'),
    path('myplate_app/', include('MyPlate_app.urls', namespace='myplate_app')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyPlate_app/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern
from . import views


app_name = 'myplate_app'

urlpatterns = [
    path('myplate_app_list/',views.FoodListView.as_view(), name='list'),
    path('set_goal/', views.GoalCreateView.as_view(), name='set_goal'),
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('previous_records/',views.PreRecordsView.as_view(), name='pre_records'),
    path('save_rec/', views.save_records, name='save_rec'),
]

MyPlate_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.
class FoodItems(models.Model):
    name = models.CharField(max_length=100, unique=True)
    calories = models.DecimalField(decimal_places=2, max_digits=10)
    image = models.ImageField(upload_to='images', null=True)

    def str(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'FoodItems'

class SetGoal(models.Model):
    goal = models.DecimalField(decimal_places=2, max_digits=10)

    def str(self):
        return self.goal

class Previous_records(models.Model):
    user = models.CharField(max_length=100)
    date = models.DateField(auto_now=True)
    totalCalories = models.DecimalField(decimal_places=2, max_digits=10)
    goal_set = models.DecimalField(decimal_places=2, max_digits=10)

    def str(self):
        return self.user

MyPlate_app/forms.py
from django import forms
from django.forms.widgets import HiddenInput

class PreRecordForm(forms.Form):
    totalCalories = forms.DecimalField(max_digits=10, decimal_places=2, widget=HiddenInput, initial={} )
    cc_myself = forms.BooleanField(required=False)

MyPlate/views.py
import requests
from bs4 import BeautifulSoup
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class LoggedIn(TemplateView):
    template_name = 'loggedIn.html'

MyPlate_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, TemplateView
from .models import FoodItems, Previous_records, SetGoal
from django.urls import reverse_lazy, reverse
from .filters import FoodFilter

# Create your views here.

class FoodListView(ListView):
    model = FoodItems
    template_name = 'MyPlate_app/list.html'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['filter'] = FoodFilter(self.request.GET, queryset = self.get_queryset())
        return context

class GoalCreateView(CreateView):
    model = SetGoal
    fields = ['goal',]
    success_url = reverse_lazy('myplate_app:list')

class CheckOutView(TemplateView):
    template_name = 'MyPlate_app/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['goal'] = SetGoal.objects.values().last().get("goal")   #creates a dict with key value pair, where id and goal are the keys. The last() method is used to retrieve the last value. get() method retrives the value of the key 'goal'
        return context

def save_records(request):
    if request.method=="POST":
        user = request.POST.get('user', '')
        totalCalories= request.POST.get('totalCalories', '')
        goal=request.POST.get('goal_set', '')

        pre_records = Previous_records(user= user, totalCalories=totalCalories, goal_set=goal,)
        pre_records.save()
        return redirect('../previous_records')
    return render(request, 'MyPlate_app/save_rec.html')

class PreRecordsView(ListView):
    model = Previous_records
    template_name = 'MyPlate_app/previous_records.html'
    context_object_name = 'records'

    def get_queryset(self):
        filtered_list = Previous_records.objects.filter(user = self.request.user.first_name + ' ' + self.request.user.last_name)
        return filtered_list.order_by('-date')[:10]
    

MyPlate_app/templates/MyPlate_app/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    body{
        background-image: linear-gradient(to right, aqua, rgb(150, 68, 226), rgb(205, 43, 226))
    }
    ul{
        font-size: 18px;
    }
    .total{
        display: inline;
        font-size: 23px;
        float: right;
        margin-top: 15px;
    }
    .goal{
        font-size: 23px;
        margin-top: 15px;
    }
    .save{
        background-color: #201585;
        color: aliceblue;
        font-size: 20px;
    }
    .save:hover{
        color: aliceblue;
    }
    section{
      margin-top: 15px;
      border: 1px solid black;
      border-radius: 20px;
      background-color: white;
      padding-right: 15px;
      padding-left: 15px;
      padding-bottom: 15px;
      margin-bottom: 15px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
<h3>Your selected food items are:</h1>
<section>
<div class="my-4">
    <ul class="list-group" id="items">
    </ul>
    <p class="total">Total Calories : <span id="total_calories"></span></p>
    <p class="goal">Goal : <span id="goal">{{goal}}</span></p>
    <h3 id="compare"></h3>
</div>
<a href="{% url 'myplate_app:save_rec' %}" class="btn save">Save record</a>
</section>
</div>
{% endblock %}

{% block js %}
<script>
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));
}
var total_calories = 0;
var sum = 0;
for (item in cart) {
    let name = cart[item][1];
    let qty = cart[item][0];
    let calories = cart[item][2];
    sum = sum + qty;
    total_calories = parseFloat(total_calories + qty * calories);
    if(qty != 0){
        mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                    <span class="btn btn-dark">${qty}</span>
                </li>`
        $('#items').append(mystr);
    }
}
document.getElementById("total_calories").innerHTML = total_calories;

var goal = parseFloat(document.getElementById("goal").innerHTML);

if(goal > total_calories){
    diff = parseFloat(goal - total_calories).toFixed(2);
    str = `You are ${diff} calories away from reaching your goal.`
    $('#compare').append(str);
    document.getElementById("compare").style.color = "orange";
}
else if(goal == total_calories){
    str = `Congratulations you have reached your goal..!! You consumed ${goal} calories.`
    $('#compare').append(str);
    document.getElementById("compare").style.color = "green";
}
else{
    diff = parseFloat(total_calories - goal).toFixed(2);
    str = `You exceeded your goal by ${diff} calories.`
    $('#compare').append(str);
    document.getElementById("compare").style.color = "red";
}
localStorage.setItem("totalCalories", total_calories);
localStorage.setItem("goal_set", goal);

</script>

{% endblock %}

MyPlate_app/templates/MyPlate_app/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block style %}
<style>
  body{
    background-image: linear-gradient(to right, aqua, rgb(150, 68, 226), rgb(205, 43, 226))
  }
  form{
    width: 300px;
    text-align: center;
    font-size: 20px;
    margin-bottom: 15px;
  }
  .search{
    margin-top: 10px;
    background-color: #2b062d;
    font-size: 18px;
    margin-bottom: 10px;
    color: beige;
  }
  .search:hover{
    color: rgb(214, 214, 199);
  }
</style>
{% endblock %}
{% block content %}
<div class="container">
<center>
<form method="GET" class="filter">
  {{filter.form|bootstrap}}
  <button type="submit" class="search btn">Search</button>
</form>
</center>
<div class="row row-cols-1 row-cols-md-4 g-4" id="main-div">
    {% for food in filter.qs %}
        <div class="col">
          <div class="card text-center">
            <img src="{{food.image.url}}" class="card-img-top" alt="{{food.name}}" height="250">
            <div class="card-body">
              <h4 class="card-title" id="name{{food.id}}">{{food.name}}</h4>
              <h5 class="card-text">Calories = <span id="calories{{food.id}}">{{food.calories}}</span></h5>
              <span id="food{{food.id}}" class="food"><button class="btn btn-primary cart" class="cart" id="{{food.id}}">Add to Cart</button></span>
            </div>
          </div>
        </div>
    {% endfor %}
</div>
<a href="{% url 'myplate_app:checkout' %}" class="search btn">Checkout</a>
</div>
{% endblock %}

{% block js %}
<script>
  if(localStorage.getItem('cart') == null)
  {
    var cart={};
  }
  else{
    cart = JSON.parse(localStorage.getItem('cart'));
  }

  $('.food').on('click', 'button.cart', function() {
    var idstr = this.id.toString();
    if (cart[idstr] != undefined) {
        qty = cart[idstr][0] + 1;
        
    } else {
        qty = 1;
        name = document.getElementById('name'+idstr).innerHTML
        calories = document.getElementById('calories'+idstr).innerHTML
        cart[idstr] = [qty, name, parseFloat(calories)];
    }
    updateCart(cart);
    });

  function updateCart(cart) {
    var x = $('#main-div .food').length;
    for (var item in cart) {
      for(let j=0; j<x; j++){
        if('food'+item == document.getElementsByClassName("food")[j].id){
          document.getElementById('food'+item).innerHTML = "<button id='minus" + item + "' class='btn btn-primary minus'>-</button> <span id='val" + item + "''>" + cart[item][0] + "</span> <button id='plus" + item + "' class='btn btn-primary plus'> + </button>";
        }
        else{
          continue;
        }
      } 
    }
    localStorage.setItem('cart', JSON.stringify(cart));
  }

  $('.food').on("click", "button.minus", function() {
    a = this.id.slice(5, );
    cart[a][0] = cart[a][0] - 1;
    cart[a][0] = Math.max(0, cart[a][0]);
    document.getElementById('val' + a).innerHTML = cart[a][0];
    updateCart(cart);
  });

  $('.food').on("click", "button.plus", function() {
    a = this.id.slice(4, );
    cart[a][0] = cart[a][0] + 1;
    document.getElementById('val' + a).innerHTML = cart[a][0];
    updateCart(cart);
  });
</script>
{% endblock %}

MyPlate_app/templates/MyPlate_app/previous_records.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<style>
    body{
      background-image: linear-gradient(to right, aqua, rgb(150, 68, 226), rgb(205, 43, 226))
    }
    table{
        text-align: center;
        margin-top: 25px;
    }
    h1{
        text-align: center;
        font-family: 'Josefin Sans', sans-serif;
        margin-top: 25px;
    }
    th{
        font-size: 20px;
    }
    td{
        font-size: 17px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
<h1>{{user.first_name}} {{user.last_name}}, here are your previous records:</h1>
<center>
<table class="table table-dark" style="width: 70%;">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col" style="width: 32.5%;">Goal</th>
        <th scope="col" style="width: 35%;">Calories consumed</th>
      </tr>
    </thead>
    <tbody>
    {% for record in records %}
      <tr>
        <td>{{record.date}}</td>
        <td>{{record.goal_set}}</td>
        <td>{{record.totalCalories}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</center>
</div>
{% endblock %}

{% block js %}
<script>
    localStorage.clear();
</script>
{% endblock %} 

MyPlate_app/templates/MyPlate_app/save_rec.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<style>
    section{
        height: 200px;
        width: 400px;
        margin-top: 200px;
        margin-left: 375px;
        text-align: center;
    }
    body{
        background-image: url(../../static/images/bg3.jpg);
        background-repeat: no-repeat;
        background-size: cover;
    }
    .btn{
        margin-top: 10px;
        background-color: #236b32;
        color: white;
    }
    .btn:hover{
        color: white;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
<section>
<h3>Name : {{user.first_name}} {{user.last_name}}</h2>
<h3>Goal set : <span id="goal"></span></h2>
<h3>Total calories consumed : <span id="total_calories"></span></h2>
<form method="POST" action="/myplate_app/save_rec/">
    {% csrf_token %}
    <input type="hidden" name="user" id="user" value="{{ user.first_name }} {{user.last_name}}">
    <input type="hidden" name="totalCalories" id="totalCalories">
    <input type="hidden" name="goal_set" id="goal_set">
    <button type="submit" class="btn">Check Previous Records</button>
</form>
</section>
</div>
{% endblock %}
{% block js %}
<script>
    var goal = localStorage.getItem('goal_set');
    var calories = localStorage.getItem('totalCalories');
    document.getElementById("goal").innerHTML = goal;
    document.getElementById("total_calories").innerHTML = calories;
    $('#totalCalories').val(calories);
    $('#goal_set').val(goal);
</script>
{% endblock %}

MyPlate_app/templates/MyPlate_app/setgoal_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block style %}
<style>
    body{
        background-image: url(../../static/images/doodle2.jpg);
        background-repeat: no-repeat;
        background-size: cover;
    }
    section{
        border: 1px solid black;
        background-color: rgb(0, 0, 0, 0.6);
        height: 200px;
        width: 450px;
        margin-top: 150px;
        margin-left: 350px;
        border-radius: 20px;
    }
    form{
        font-size: 35px;
        text-align: center;
        color: white;
        margin-left: 15px;
        margin-right: 15px;
        margin-top: 20px;
    }
    .btn{
        font-size: 20px;
        border-radius: 12px;
        margin-top: 10px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <section>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|bootstrap}}
    <input type="submit" class="btn btn-success" value="Set Goal">
    </form>
    </section>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Plate</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=STIX+Two+Math&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet">
    {% block style %}

    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mynav" role="navigation" id="navbar">
        <div class="container-fluid">
          <a class="navbar-brand mynav logo" href="{% url 'index' %}" style="font-family: 'Dancing Script', cursive; font-size: 25px;">My Plate</a>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li class="nav-item"> <a class="nav-link" href="{% url 'myplate_app:set_goal' %}" style="font-size: 20px;">Set Goal</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'myplate_app:list' %}" style="font-size: 20px;">Food Items</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'myplate_app:pre_records' %}" style="font-size: 20px;">Previous records</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'account_logout' %}" style="font-size: 20px;">Logout</a> </li>
              {% else %}
                <li class="nav-item"> <a class="nav-link" href="{% url 'index' %}" style="font-size: 20px;">Home</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'account_login' %}" style="font-size: 20px;">Login</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'account_signup' %}" style="font-size: 20px;">Sign Up</a> </li>
              {% endif %}
            </ul>
          </div>
      </nav>
        {% block content %}

        {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
{% block js %}

{% endblock %}
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<style>
    body{
        background-image: linear-gradient(to right, aqua, rgb(150, 68, 226), rgb(205, 43, 226))
    }
    img{
        margin-top: 10px;
        height: 600px;
        width: 600px;
        float: right;
        border-radius: 300px;
        margin-bottom: 10px;
        margin-right: 15px;
    }
    h1{
        padding-top: 25px;
        font-size: 80px;
        margin-left: 45px;
        font-family: 'STIX Two Math', serif;
    }
    p{
        font-size: 23px;
        margin-left: 45px;
        padding-top: 15px;
    }
    .btn{
        margin-left: 45px;
        margin-top: 10px;
        background-color: #191970;
        color: beige;
        font-size: 19px;
    }
    .btn:hover{
        color: beige;
    }
</style>
{% endblock %}
{% block content %}
<div>
    <section>
        <img src="{% static 'images/bg.jpg' %}" alt="">
    </section>
    <div class="container">
        <h1>Fitness starts <br> with what you <br> eat.</h1>
        <p>Take control of your goals. Track calories, and <br> log activities with <b><i>My Plate</i></b>.</p>
        <a href="{% url 'account_login' %}" class="btn">Let's get started</a>
    </div>
</div>
{% endblock %}